BINANCE_SECRET_KEY = "Vp84Am8k9PfobrU0xth9tT1uFtSUyU8p6rENbzzim9ZE2Z4FOgUWDNpjqUM3CoRj"
BINANCE_API_KEY = "vJHuVl2E3Vz6Uej8JbShhHcJaus53Vt5zJ1LpBXCmCTZ71hGFj1Qd50Q4CJK5irS"

CMC_KEY = "0197e5a1-06a8-4cec-8f2e-e33ec2b5c06c"

GMAIL_SENDER = 'cloud.trading.app'
GMAIL_SENDER_PW = 'fae.+3f154'
MAIL_RECIEVER = 'mads.steenfeldt.foss@gmail.com'
SHEETS_ID = '1ckQ3JaGAsowqNDCp_DrqQxqfvpPrFvY3TpYrtewrwEE'

TIMEZONE = "Europe/Berlin"

[SERVICE_ACC] 

"type"= "service_account"
"project_id"= "crypto-sheets-310419"
"private_key_id"= "02bf6fcf60e55a32da95ac2d422baf7d4eabaa9a"
"private_key"= "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQD4a6irqxZgFZmo\n4GZ4Gi2QC3maE5ClYjZzG1ieq41pCi36R1HGOdxVt3Wc6YAZiKb+G9onk0gHtGwK\nJZYDhM9vBy7Ie5rpyW64pXG8zkAgjP6k71hb66ZZYiLIIBSiC63i6C0uOred+0Ac\nqZtR/AmQAl1PRtFHt/r8/HM77f9/Uqyg7pcWlhRVFMt/GPmo9N+sskYNNTK0Hh2x\nslDGCLZeZTgkxOeVynLm4vo9eRMUaVFYomqWYhjk0VFTRj0XvpTc7YEjaa51x+VI\nCYpc3cllQRYmPQXKGnILLayXwQGsC/qkbyebdqHJk0Eyvxcqww0pKn3nzvgQtZtt\nUuL3dcbrAgMBAAECggEASSRppSHalK/HblGj2fjbMW4vf44DKK6iGYITtaQNHsBA\niVA2Y4bluNcraefWL65sfKT2tnBG5P3aUaJ/aMnRyX7z51N9aRhF4VfVBSI0/2CE\nGUvfWDEp6WdbllDbwlpt+EEkDFh9d6ZiWg4WDS2IIz6O+qh/Nf6Vh6dMxnhsoa/B\nYhtScrL9smVqBbc805HXlvdsxKCXYI+UT0nv8Ea0sbUomPyGCmBKCkurk5euTHsy\nXX8tkR3991PKAr1FVLDB+i8Siy0QXzKH1wBVtLHLKDb+0028msrmIacdOjJi5MBk\nrOlr1XJi1+1A7ExsJB+DtpifmcRvjpRnf0T8n59jAQKBgQD+hH6NZQQRNMpH3u8e\nLJNgvxOOhZI2LZOqeQIf473J9PHYLDheVIbfcVTCMf+bBs/jH+K+3LVS5rSCrpDB\n2JUinm/0UOgIeFlywfxSbW8AtRrVvqiLGrArml/ZjZuS/OMaKOD6/kpnpFNtJ39L\nXQweuFDOnNkC+V0kHgJ1Cp1ObQKBgQD53hLKQCUchv1LcCxe83urY3Gqa90zs3M/\ncS0EYjRbUYumQe1YV0GbYpZrbKbevM9c6Y0A16oGqj3nZIGUeydyhgMc0amdVh9j\nicOakzUMRSLDBwq3SCbCql3Cdwv/kj9ArXbrrHreu1MHEyNztBZZjp30P9572Ak1\nPpdh+g8ztwKBgAP/BpGnxWGTx51LRcvefU3mkiMJu9r36jqh/cOMat1x6B4xy4zH\nnPqDKAaIjG/dsoPpa0D97CbqEml+3iz8/pJ1lGJspsgDQ7xGiXSt3TFQpqQ2gyTz\n/VIh8WFUFN5A9Dvj6mxmc7qe3OR420nOozMUR8iGs+2VBr5bbkRyLzgdAoGBAMMp\nBRwbheEGPojRkJaJLqrq/TjTDu721qlSyIqH+cTpqF2vWKaLYJ7xHfPB5YRLjNtR\nP+TMjeyuw7Mb+Wnz1xfIPF4iFIzjW5jvXWw6VlDDHyedNG17WWrqjlj5itGPdQAb\nfKsPCNk3Dt6TwDj7DAnfLtg7mpa4YljIDo1kNsN5AoGBAMl6sds8gwMv368ZFY8I\nX5kxjpra/wjYZLsXJwEeI2j0XicNSj/iMNwM7mCk4IDXAFEM7CHFk+gfWvYK6jqR\n78MAReKFwODEe3rjZI2kmQGua/0UGLhruzMn+gCOXJBQO+SSFz5YAsGXiOfvetoL\naQ2DdFGYNYUkUNJ60YWKXVqk\n-----END PRIVATE KEY-----\n"
"client_email"= "crypto-sheets@crypto-sheets-310419.iam.gserviceaccount.com"
"client_id"= "108789072083870764284"
"auth_uri"= "https://accounts.google.com/o/oauth2/auth"
"token_uri"= "https://oauth2.googleapis.com/token"
"auth_provider_x509_cert_url"= "https://www.googleapis.com/oauth2/v1/certs"
"client_x509_cert_url"= "https://www.googleapis.com/robot/v1/metadata/x509/crypto-sheets%40crypto-sheets-310419.iam.gserviceaccount.com"

