# Generated by Django 3.2.3 on 2021-05-25 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0003_alter_tag_tag_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag_group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='tags.taggroup'),
        ),
    ]
