# Generated by Django 3.2.4 on 2021-08-01 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exchanges', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('currencies', '0001_initial'),
        ('strategies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('bot_execute_trades', models.BooleanField(default=False)),
                ('bot_email_notify', models.BooleanField(default=False)),
                ('public', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('strategy', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='strategies.strategy')),
            ],
            options={
                'unique_together': {('owner', 'name')},
            },
        ),
        migrations.CreateModel(
            name='PortfolioAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average', models.DecimalField(blank=True, decimal_places=10, max_digits=18, null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currencies.currency')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolios.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=10, max_digits=18)),
                ('price', models.DecimalField(decimal_places=10, max_digits=18)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('buy_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_currency', to='currencies.currency')),
                ('exchange', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='exchanges.exchange')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolios.portfolio')),
                ('sell_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sell_currency', to='currencies.currency')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('assets', models.JSONField()),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolios.portfolio')),
            ],
            options={
                'verbose_name_plural': 'Portfolio log entries',
            },
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=10, max_digits=18)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currencies.currency')),
                ('exchange', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='exchanges.exchange')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolios.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('BATCH', 'BATCH'), ('BOT', 'BOT'), ('OTHER', 'OTHER')], default='OTHER', max_length=5)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('SPOT', 'SPOT'), ('FLEX', 'FLEX'), ('LOCK', 'LOCK')], default='SPOT', max_length=4)),
                ('amount', models.DecimalField(blank=True, decimal_places=10, max_digits=18, null=True)),
                ('apr', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=7, null=True)),
                ('stake_start', models.DateTimeField(blank=True, null=True)),
                ('stake_end', models.DateTimeField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolios.portfolioasset')),
                ('exchange', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='exchanges.exchange')),
            ],
            options={
                'unique_together': {('asset', 'exchange', 'status', 'stake_end', 'stake_start', 'apr')},
            },
        ),
        migrations.CreateModel(
            name='PortfolioParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strategies.strategyparameter')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolios.portfolio')),
            ],
            options={
                'unique_together': {('portfolio', 'parameter')},
            },
        ),
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('key', django_cryptography.fields.encrypt(models.CharField(max_length=200))),
                ('secret', django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=200, null=True))),
                ('data', django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=200, null=True))),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchanges.exchange')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolios.portfolio')),
            ],
            options={
                'verbose_name_plural': 'Credentials',
                'unique_together': {('owner', 'exchange', 'portfolio')},
            },
        ),
    ]
