# Generated by Django 3.2.4 on 2021-08-01 22:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 1, 22, 37, 48, 780768, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='trade',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 1, 22, 37, 48, 780147, tzinfo=utc)),
        ),
    ]
