# Generated by Django 3.2.3 on 2021-05-26 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0005_auto_20210526_1820'),
        ('exchanges', '0005_delete_credentials'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolios', '0002_portfolioparameter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_amount', models.DecimalField(decimal_places=10, max_digits=18)),
                ('sell_amount', models.DecimalField(decimal_places=10, max_digits=18)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('buy_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_currency', to='currencies.currency')),
                ('exchange', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='exchanges.exchange')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolios.portfolio')),
                ('sell_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sell_currency', to='currencies.currency')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=4)),
                ('amount', models.DecimalField(decimal_places=10, max_digits=18)),
                ('average', models.DecimalField(decimal_places=10, max_digits=18)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('apr', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=7)),
                ('stake_start', models.DateTimeField(blank=True, null=True)),
                ('stake_end', models.DateTimeField(blank=True, null=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currencies.currency')),
                ('exchange', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='exchanges.exchange')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolios.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=10, max_digits=18)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currencies.currency')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolios.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('api_key', django_cryptography.fields.encrypt(models.CharField(max_length=200))),
                ('api_secret', django_cryptography.fields.encrypt(models.CharField(max_length=200))),
                ('api_payload', django_cryptography.fields.encrypt(models.CharField(max_length=200))),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchanges.exchange')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolios.portfolio')),
            ],
            options={
                'verbose_name_plural': 'Credentials',
            },
        ),
    ]
