# Generated by Django 3.2.4 on 2021-06-04 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0002_auto_20210604_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioasset',
            name='status',
            field=models.CharField(choices=[('SPOT', 'Instantly tradeable'), ('FLEX', 'Tradeable with action'), ('LOCK', 'Not tradeable')], default='SPOT', max_length=4),
        ),
    ]
