# Generated by Django 3.2.4 on 2021-06-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0003_alter_portfolioasset_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfoliologentry',
            options={'verbose_name_plural': 'Portfolio log entries'},
        ),
        migrations.AlterField(
            model_name='portfolioasset',
            name='close_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
