# Generated by Django 3.2.3 on 2021-05-30 16:46

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0003_credentials_deposit_portfolioasset_trade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentials',
            name='api_payload',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=200, null=True)),
        ),
        migrations.AlterField(
            model_name='credentials',
            name='api_secret',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=200, null=True)),
        ),
    ]
