# Generated by Django 3.2.4 on 2021-08-11 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0004_portfolio_modifiied'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='diff_matrix',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
