# Generated by Django 3.2.4 on 2021-06-05 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0004_auto_20210605_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioasset',
            name='average',
        ),
    ]
