# Generated by Django 3.2.3 on 2021-05-30 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0005_auto_20210530_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioasset',
            name='apr',
        ),
        migrations.RemoveField(
            model_name='portfolioasset',
            name='stake_end',
        ),
        migrations.RemoveField(
            model_name='portfolioasset',
            name='stake_start',
        ),
        migrations.AddField(
            model_name='portfolioasset',
            name='flex_apr',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='portfolioasset',
            name='flex_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolioasset',
            name='locked_apr',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='portfolioasset',
            name='locked_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='portfolioasset',
            name='locked_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
