# Generated by Django 3.2.4 on 2021-06-06 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0006_auto_20210605_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioasset',
            name='status',
            field=models.CharField(choices=[('SPOT', 'SPOT'), ('FLEX', 'FLEX'), ('LOCK', 'LOCK')], default='SPOT', max_length=4),
        ),
    ]
