# Generated by Django 3.2.3 on 2021-05-30 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0006_auto_20210530_1726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolioasset',
            old_name='modified',
            new_name='timestamp',
        ),
    ]
