# Generated by Django 3.2.3 on 2021-05-30 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0007_rename_modified_portfolioasset_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioasset',
            name='added_at',
        ),
    ]
