# Generated by Django 3.2.3 on 2021-05-30 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0008_remove_portfolioasset_added_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioasset',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
