# Generated by Django 3.2.4 on 2021-06-06 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0001_initial'),
        ('currencies', '0004_auto_20210605_1654'),
        ('portfolios', '0008_alter_portfolioasset_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='portfolioasset',
            unique_together={('portfolio', 'currency', 'exchange', 'status', 'close_time', 'stake_end', 'stake_start', 'apr')},
        ),
    ]
