# Generated by Django 3.2.4 on 2021-06-10 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0009_alter_portfolioasset_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioasset',
            name='source',
            field=models.CharField(choices=[('BATCH', 'BATCH'), ('BOT', 'BOT'), ('OTHER', 'OTHER')], default='OTHER', max_length=5),
        ),
    ]
