# Generated by Django 3.2.3 on 2021-05-30 20:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0005_auto_20210530_2048'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exchanges', '0006_auto_20210530_2048'),
        ('portfolios', '0009_portfolioasset_active'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='credentials',
            unique_together={('owner', 'exchange', 'portfolio')},
        ),
        migrations.AlterUniqueTogether(
            name='portfolio',
            unique_together={('owner', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='portfolioparameter',
            unique_together={('portfolio', 'parameter')},
        ),
    ]
