# Generated by Django 3.2.3 on 2021-06-03 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0010_auto_20210530_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioasset',
            name='flex_apr',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='portfolioasset',
            name='locked_apr',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=7, null=True),
        ),
    ]
