# Generated by Django 3.2.4 on 2021-06-11 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0001_initial'),
        ('portfolios', '0010_portfolioasset_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioparameter',
            name='strategy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='strategies.strategy'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='portfolioparameter',
            unique_together={('portfolio', 'parameter', 'strategy')},
        ),
    ]
