# Generated by Django 3.2.4 on 2021-06-12 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0001_initial'),
        ('portfolios', '0011_auto_20210611_2340'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='portfolioparameter',
            unique_together={('portfolio', 'parameter')},
        ),
        migrations.RemoveField(
            model_name='portfolioparameter',
            name='strategy',
        ),
    ]
