# Generated by Django 3.2.4 on 2021-06-19 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0012_auto_20210612_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='bot_email_notify',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='bot_execute_trades',
            field=models.BooleanField(default=False),
        ),
    ]
