# Generated by Django 3.2.4 on 2021-07-09 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0004_auto_20210605_1654'),
        ('exchanges', '0001_initial'),
        ('portfolios', '0013_auto_20210619_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioasset',
            name='average',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=18, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='portfolioasset',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='portfolioasset',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='portfolioasset',
            name='apr',
        ),
        migrations.RemoveField(
            model_name='portfolioasset',
            name='close_time',
        ),
        migrations.RemoveField(
            model_name='portfolioasset',
            name='exchange',
        ),
        migrations.RemoveField(
            model_name='portfolioasset',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='portfolioasset',
            name='source',
        ),
        migrations.RemoveField(
            model_name='portfolioasset',
            name='stake_end',
        ),
        migrations.RemoveField(
            model_name='portfolioasset',
            name='stake_start',
        ),
        migrations.RemoveField(
            model_name='portfolioasset',
            name='status',
        ),
        migrations.CreateModel(
            name='PortfolioPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('close_time', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(choices=[('BATCH', 'BATCH'), ('BOT', 'BOT'), ('OTHER', 'OTHER')], default='OTHER', max_length=5)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('SPOT', 'SPOT'), ('FLEX', 'FLEX'), ('LOCK', 'LOCK')], default='SPOT', max_length=4)),
                ('amount', models.DecimalField(blank=True, decimal_places=10, max_digits=18, null=True)),
                ('apr', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=7, null=True)),
                ('stake_start', models.DateTimeField(blank=True, null=True)),
                ('stake_end', models.DateTimeField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolios.portfolioasset')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currencies.currency')),
                ('exchange', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='exchanges.exchange')),
            ],
            options={
                'unique_together': {('asset', 'currency', 'exchange', 'status', 'close_time', 'stake_end', 'stake_start', 'apr')},
            },
        ),
    ]
