# Generated by Django 3.2.4 on 2021-08-02 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameter',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='parametertype',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='strategy',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='strategyparameter',
            name='created_at',
        ),
    ]
