# Generated by Django 3.2.3 on 2021-05-25 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0003_parameter_strategyparameter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='strategy',
            options={'verbose_name_plural': 'Strategies'},
        ),
    ]
