# Generated by Django 3.2.3 on 2021-05-25 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
