# Generated by Django 3.2.3 on 2021-05-26 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0004_alter_credentials_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Credentials',
        ),
    ]
