# Generated by Django 3.2.3 on 2021-05-30 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0005_delete_credentials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='api_url',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='web_url',
            field=models.URLField(unique=True),
        ),
    ]
