# Generated by Django 3.2.3 on 2021-05-25 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0004_price_volume'),
        ('watchlists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchlistCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currencies.currency')),
                ('watchlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watchlists.watchlist')),
            ],
        ),
    ]
