# Generated by Django 3.2.3 on 2021-05-25 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlists', '0002_watchlistcurrency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watchlistcurrency',
            options={'verbose_name_plural': 'Watchlist currencies'},
        ),
    ]
