# Generated by Django 3.2.3 on 2021-05-30 20:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('currencies', '0006_auto_20210530_2048'),
        ('watchlists', '0003_alter_watchlistcurrency_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='watchlist',
            unique_together={('owner', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='watchlistcurrency',
            unique_together={('watchlist', 'currency')},
        ),
    ]
