# Generated by Django 3.2.4 on 2021-06-04 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
