# Generated by Django 3.2.3 on 2021-05-25 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='alternative_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
