# Generated by Django 3.2.3 on 2021-05-25 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0003_currencytag_price_tag_taggroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='volume',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=24),
        ),
    ]
