# Generated by Django 3.2.3 on 2021-05-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0004_price_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='web_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='whitepaper_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
