# Generated by Django 3.2.3 on 2021-05-31 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0009_alter_currencytag_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=10, max_digits=18)),
                ('mcap_total', models.PositiveBigIntegerField()),
                ('mcap_rank', models.SmallIntegerField()),
                ('pct_change_24h', models.DecimalField(decimal_places=5, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='MCAPTotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('mcap_total', models.PositiveBigIntegerField()),
            ],
        ),
    ]
