# Generated by Django 3.2.3 on 2021-05-31 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0011_currencystat_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencystat',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
